### ISSUE TITLE
[ux] seekbar tap vs click different behavior 

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/player#23]
When you tab on trackpad vs click (hard) seekbar seeks differently:

Video: http://cl.ly/2s0q0n263L3g

First seeks are hard click and seconds are tap

**Comment by youzi** [comment]
@nikoloza I'm using the :active state to cancel the animation, this apparently does not fire on "tap". I'm now also canceling it on 'loading' (which should fire when seeking). Testing on develop

**Comment by nikoloza** [comment]
but do you need transition on progress?

**Comment by youzi** [comment]
@nikoloza The progress bar gets updated every .500ms. When playing short videos, this isn't very pretty — that's why I added the transition. If it remains buggy, I will remove it.
