### ISSUE TITLE
[adblock] How to handle adblock

### ISSUE THREAD

**Issue by youzi** [vigour-io/player#27]
Right now having adblock activated will successfully block ads. We need to decide if this is the behaviour we want. 

Alternatively we can disable the player, showing a message to disable adblock, in which case we need a design for this.

/cc @gideonvd @chloetemple

**Comment by youzi** [comment]
@gideonvd @chloetemple 
In vigour-io/sbs#133 the request is made to disable the player when adBlock is enabled. Do you think this should be default behaviour?

**Comment by chloetemple** [comment]
@youzi that's not ideal in terms of ux but ultimately this is a business decision so we should go with what they are suggesting. I confirmed this with @gideonvd also.

**Comment by gideonvd** [comment]
@youzi make sure to also look at this ticket. It's related and required for VIMN. 
https://github.com/vigour-io/mtv-play/issues/183

**Comment by youzi** [comment]
Disabling video playback when adblock is enabled (and ads are configured)
